export{default as IndicadorCarga} from './IndicadorCarga'
//export{default as Boton} from './Boton'
//export{default as TextInput} from './TextInput'
//export{default as Titulo} from './Titulo'
//export{default as Error} from './Error'